### ISSUE TITLE
Bioconductor, biopython, bioconda, usegalaxy

### ISSUE THREAD

**Issue by alphaCTzo7G** [danielecook/Awesome-Bioinformatics#36]
The above packages: bioconductor, biopython, bioconda, usegalaxy are quite popular in the bioinformatics community.

Shoud we add those to the list of tools?

**Comment by sdhutchins** [comment]
has their been a PR for this yet? @alphaCTzo7G and @erictleung

**Comment by erictleung** [comment]
@sdhutchins not yet, so go for it if you're interested and have time! :+1:

**Comment by vinisalazar** [comment]
Im shocked these aren't there yet. I'll see if I can submit a PR today

**Comment by vinisalazar** [comment]
PR submitted

**Comment by erictleung** [comment]
Closed by #45
