### ISSUE TITLE
Add section for slack groups

### ISSUE THREAD

**Issue by bganglia** [danielecook/Awesome-Bioinformatics#49]
I have been scouring the web for bioinformatics slack groups, and wanted to share the ones I have found. 

Would you be willing to add a section for slack groups? If not, I could also create my own list.

**Comment by danielecook** [comment]
Hello @bganglia - sure I can add a few. Or you can via pull request. Post the links here if you want me to add.

Thanks!

**Comment by bganglia** [comment]
@danielecook I can open a PR with mine, and would love to see yours too.

**Comment by danielecook** [comment]
@bganglia ping
