### ISSUE TITLE
Add github actions for TOC and link checking

### ISSUE THREAD

**Issue by danielecook** [danielecook/Awesome-Bioinformatics#50]

**Comment by TGotwig** [comment]
TOC and link checking? 🤔

**Comment by danielecook** [comment]
@TGotwig I added this actually!

https://github.com/danielecook/Awesome-Bioinformatics/blob/master/.github/workflows/toc.yml
https://github.com/danielecook/Awesome-Bioinformatics/blob/master/.github/workflows/url-check.yml
