### ISSUE TITLE
Prioritizing links to repositories 🔗

### ISSUE THREAD

**Issue by TGotwig** [danielecook/Awesome-Bioinformatics#56]
I would suggest to always link to the source-code repository of an project in order to have more consistency, because it's much easier to go from there to the portfolio site than the other way around, sometimes the source-code repository is not even mentioned on the portfolio website 😬

**Comment by danielecook** [comment]
I agree - maybe we can add a [ docs | project ] links as well.

**Comment by TGotwig** [comment]
Hmm I would suggest `[ publication | web ]`, if there are multiple publications, then I would name them `publication#1` `publication#2` etc. 🙂

**Comment by TGotwig** [comment]
Working on that for the Visualization-section 👨‍💻🖼
